alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

name: secretlab-assessment

region: sgp1

services:
  - name: web-services
    git:
      branch: master
      repo_clone_url: https://github.com/syamimhazmi/secretlab-assessment.git
    github:
      repo: syamimhazmi/secretlab-assessment
      branch: master
      # disable this, only deploy once gh action finished its build
      deploy_on_push: true
    http_port: 80
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    dockerfile_path: ./Dockerfile
    liveness_health_check:
      initial_delay_seconds: 5
      success_threshold: 2
      http_path: /health
    envs:
      - key: APP_NAME
        value: "Secretlab Assessment"
        scope: RUN_TIME
        type: GENERAL
      - key: APP_ENV
        value: staging
        scope: RUN_TIME
        type: GENERAL
      - key: APP_KEY
        value: base64:hJzQK1Tk7AhCbqhqVuuhqKFzQ0JRktB3e+AteIvbQJI=
        scope: RUN_TIME
        type: SECRET
      - key: APP_DEBUG
        value: "false"
        scope: RUN_TIME
        type: GENERAL
      - key: APP_URL
        value: ${APP_URL}
        scope: RUN_TIME
        type: GENERAL
      - key: LOG_CHANNEL
        value: stack
        scope: RUN_TIME
        type: GENERAL
      - key: LOG_STACK
        value: single
        type: GENERAL
      - key: LOG_LEVEL
        value: debug
        scope: RUN_TIME
        type: GENERAL
      - key: DB_CONNECTION
        value: pgsql
        scope: RUN_TIME
        type: GENERAL

    databases:
      - name: db
        engine: PG
        version: "13"
        production: false
        db_name: secretlab-assessment
        db_user: admin
