alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

name: secretlab-assessment

region: sgp1

services:
  - name: web-services
    git:
      branch: master
      repo_clone_url: https://github.com/syamimhazmi/secretlab-assessment.git
    github:
      repo: syamimhazmi/secretlab-assessment
      branch: master
      # disable this, only deploy once gh action finished its build
      deploy_on_push: false
    http_port: 80
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    dockerfile_path: ./Dockerfile
